# Configuração do Banco de Dados PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d9fuo5reo5us738ognfg-a.ohio-postgres.render.com:5432/wsproject?sslmode=require
spring.datasource.username=admneto
spring.datasource.password=7DxzdDliY72oaJ6XvzNeqV3ob16Kx5cm
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 

# Segurança / JWT
jwt.secret=MYJWTSECRET 
jwt.expiration=3600000